#!/bin/bash
echo "Introduzca un puerto"
read puerto
if   grep -oq  "$puerto" /etc/apache2/ports.conf  ; then
	echo "Ya esta escrito ese puerto"
else 
 	echo "Listen $puerto" >>  /etc/apache2/ports.conf
 	echo "Puerto añadido"
fi
